<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
  <PropertyGroup>
    <Version>0.0.0.9</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="credentials\google.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="credentials\google.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.69.0.3694" />
  </ItemGroup>
</Project>
