<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.12</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="credentials\google.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SubDataLogger.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="credentials\google.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.69.0.3694" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DalamudPackager" Version="15.0.0" />
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
  </ItemGroup>

</Project>
